### PR TITLE
Update a json_modifications column when a version is created

### PR DESCRIPTION
**Pull request by nelseric**
Update a json_modifications column when a version is created

### CODE REVIEW

**Review by jkthorne — APPROVED** [review]
I dont know enough about this project but it looks good.
Also the tests are failing.

**Review by gmanley — CHANGES_REQUESTED** [review]
You need to update this method too: https://github.com/eligoenergy/vestal_versions/blob/master/lib/vestal_versions/deletion.rb#L33 for deletion. Also this: https://github.com/eligoenergy/vestal_versions/blob/fb0125182db20d5dc7de917334b0055d6b20021a/lib/vestal_versions/creation.rb#L65 for updating. Your current code will just set the new column on new records, it looks like.

**Comment by gmanley** [comment]
@nelseric You'll want to update the `update_version` method as well: [https://github.com/eligoenergy/vestal_versions/blob/fb0125182db20d5dc7de917334b0055d6b20021a/lib/vestal_versions/creation.rb#L65](https://github.com/eligoenergy/vestal_versions/blob/fb0125182db20d5dc7de917334b0055d6b20021a/lib/vestal_versions/creation.rb#L65)

Something like this should work:

```ruby
    def update_version
      return create_version unless v = versions.last
      v.modifications_will_change!
      modifications = v.changes.append_changes(version_changes))
      v.update_attribute(:modifications, modifications)
      v.update_attribute(:json_modifications, modifications)
      reset_version_changes
      reset_version
    end
```

**Comment by nelseric** [comment]
I think I'm going to try do do this in portal with a subclass of VestalVersions::Version

**Pull request closed without merging**
